#' Write a compensation matrix into a fcs file
#'
#' When a compensation matrix is made in flowjo it only exists in the workspace. It is applied like a mask on the fcs file.
#' In case the workspace is lost or gets corrupted, the compensation matrix is lost. To avoid that one may want to hard-code the matrix into
#' the fcs-file. This function takes a csv file of a compensation matrix as exported from flowjo and writes it into the SPILL-keyword
#' of a fcs file. Moreover, a full compensation matrix is generated: You may have noticed that a compensation matrix purely generated
#' in flowjo is not complete - spillover into channels can only be assigned for existing compensation controls. This is different to
#' a matrix generated by BDs DIVA software where spillover into all channels can be assigned, no matter if for respective channel a
#' compensation control was recorded. E.g. for a live/dead-channel we are generally only interested in spillover into the channel, not
#' which spillover comes out of it, as dead cells are not of interest in most cases.
#'
#' @param fcs_file_path character, file path to the fcs file
#' @param comp_mat_file_path character, file path to the csv file of the compensation matrix
#' @param max_match_dist numeric, maximum string distance for matching channel names using utils::adist
#' @param skip_check logical, whether to ask for confirmation by the user if channel names were matched correctly
#'
#' @return no return but an fcs file with an updated compensation matrix (SPILL keyword) on disk
#' @export
#'
#' @examples
#'\dontrun{
#'comp_mat_to_fcs(fcs_file_path = "myfolder/my_file.fcs",
#'comp_mat_file_path = "myfolder/comp_mat_export_from_flowjo.csv")
#' }
fcs_write_comp_mat <- function(fcs_file_path,
                               comp_mat_file_path,
                               max_match_dist = 1,
                               skip_check = F) {

  if (!requireNamespace("BiocManager", quietly = T)){
    utils::install.packages("BiocManager")
  }
  if (!requireNamespace("flowCore", quietly = T)){
    BiocManager::install("flowCore")
  }

  if (!file.exists(comp_mat_file_path)) {
    stop("comp_mat not found.")
  }
  if (!file.exists(fcs_file_path)) {
    stop("fcs_file not found.")
  }
  if (!methods::is(comp_mat_file_path, "character") || rev(strsplit(basename(comp_mat_file_path), "\\.")[[1]])[1] != "csv") {
    stop("comp_mat has to be character (path to a csv file).")
  }

  comp_mat <- utils::read.csv(comp_mat_file_path, header = T, row.names = 1, check.names = F)
  if (!identical(rownames(comp_mat), colnames(comp_mat))) {
    stop("colnames and rownames of comp_mat have to be equal.")
  }
  ff <- flowCore::read.FCS(fcs_file_path, truncate_max_range = F, emptyValue = F)
  sp <- flowCore::keyword(ff)[["SPILL"]]


  sp <- prep_spill(sp = sp, comp_mat = comp_mat, max_match_dist = max_match_dist, skip_check = skip_check, verbose = T)
  flowCore::keyword(ff)[["SPILL"]] <- sp
  flowCore::write.FCS(ff, fcs_file_path)
  message(fcs_file_path)
}

prep_spill <- function(sp, comp_mat, max_match_dist = 1, skip_check = T, verbose = F) {

  # sp is SPILL keyword from fcs file
  # comp_mat is the matrix generated elsewhere (e.g. FlowJo)
  # max_match_dist is the maximum allowed string distance between channel names for matching; channel names from FCCF always contain a "/" which is replaced by "_"

  original_colnames_sp <- colnames(sp)
  colnames(sp) <- gsub("/", "_", colnames(sp))

  rownames(sp) <- colnames(sp)
  if (!all(colnames(comp_mat) %in% colnames(sp))) {
    if (verbose) {
      message("Not all colnames of comp_mat found in those of the SPILLOVER keyword matrix from the FCS file.")
    }
    # match channel names
    if (any(apply(utils::adist(colnames(comp_mat), colnames(sp)), 1, min) > max_match_dist)) {
      print(colnames(comp_mat)[apply(utils::adist(colnames(comp_mat), colnames(sp)), 1, min) > max_match_dist])
      print(colnames(sp))
      stop("Too big string distances between channel names of comp_mat and FCS file. Please, check the column names or make sure you provide the correct compensation matrix.")
    }
    match_ind <- apply(utils::adist(colnames(comp_mat), colnames(sp)), 1, which.min)
    if (any(duplicated(match_ind))) {
      stop("Channel names from comp_mat not uniquely matched to channel names from FCS file.")
    }
    if (verbose) {
      message("Matched channel names:")
      print(data.frame(comp_mat = colnames(comp_mat), FCS = colnames(sp)[match_ind]))
    }
    colnames(comp_mat) <- colnames(sp)[match_ind]
    rownames(comp_mat) <- colnames(sp)[match_ind]
    if (!skip_check) {
      if (interactive()) {
        choice <- utils::menu(c("Yes", "No"), title = "Channel names matched correctly - Continue?")
        if (choice == 2) {
          return(NULL)
        }
      }
    }
  }
  for (rr in rownames(comp_mat)) {
    for (cc in colnames(comp_mat)) {
      sp[which(rownames(sp) == rr), which(colnames(sp) == cc)] <- comp_mat[which(rownames(comp_mat) == rr), which(colnames(comp_mat) == cc)]
    }
  }
  rownames(sp) <- NULL
  colnames(sp) <- original_colnames_sp

  return(sp)
}


#' Make an existing compensation matrix in a FCS neutral
#'
#' This will overwrite an existing compensation matrix in a FCS file so that
#' there are ones on the diagonal and else zeros. This is handy in order to
#' not having to type this manually in flow jo or so.
#'
#' @param fcs_file_path character, file path to the fcs file
#' @param comp_mat_keyword character, name of the keyword which holds the matrix
#' @param channel_names enter channels for comp matrix; only applied when matrix under comp_mat_keyword is missing of size 0
#'
#' @return no return, but FCS changed on disk
#' @export
#'
#' @examples
#'\dontrun{
#'compMap_neutral_to_fcs(fcs_file_path = "my/path/to/FCSfile.fcs")
#' }
fcs_write_comp_mat_neutral <- function(fcs_file_path,
                                       comp_mat_keyword = "SPILL",
                                       channel_names = NULL) {

  if (!requireNamespace("BiocManager", quietly = T)){
    utils::install.packages("BiocManager")
  }
  if (!requireNamespace("flowCore", quietly = T)){
    BiocManager::install("flowCore")
  }
  if (!file.exists(fcs_file_path)) {
    stop("fcs_file not found.")
  }


  ff <- flowCore::read.FCS(fcs_file_path, truncate_max_range = F, emptyValue = F)

  new_key <- F
  if (!comp_mat_keyword %in% names(flowCore::keyword(ff))) {
    candidates <- grep("Spill", names(flowCore::keyword(ff)), value = T, ignore.case = T)
    if (length(candidates > 0)) {
      message("comp_mat_keyword not found in keywords of FCS file. You may try one of these: ", paste(candidates, collapse = ","))
    } else {
      message("comp_mat_keyword not found in keywords of FCS file and also no other Keyword with 'Spill' in it. Will assign a new keyword for comp matrix: 'SPILL' and will create matrix from channel names in FCS parameters.")
      new_key <- T
      comp_mat_keyword <- "SPILL"
      flowCore::keyword(ff)[[comp_mat_keyword]] <- matrix(nrow = 0, ncol = 0)
    }
  }

  sp <- flowCore::keyword(ff)[[comp_mat_keyword]]
  if (!methods::is(sp, "matrix") || nrow(sp) == 0) {
    if (!methods::is(sp, "matrix")) {
      message(comp_mat_keyword, " in FCS file is not a matrix. Will create matrix from channel names in FCS parameters.")
    } else if (nrow(sp) == 0 && !new_key) {
      message("comp_mat in FCS file has zero rows. Will create matrix from channel names in FCS parameters.")
    }
    if (is.null(channel_names)) {
      channel_names <- flowCore::parameters(ff)@data$name
      channel_names <- channel_names[which(!grepl("HDR|Time|FSC|SSC|BSC", channel_names, ignore.case = T))]
      message("Channels included in matrix are: ", paste(channel_names, collapse = ", "), ". If wrong or some are missing, please provide manually via the channel_names argument.")
    } else {
      temp <- channel_names[!which(channel_names %in% flowCore::parameters(ff)@data$name)]
      if (length(temp) > 0) {
        message("These channel_names were not found: ", paste(temp, collapse = ","), ". They are not included in the newly generated comp matrix.")
      }
      channel_names <- channel_names[which(channel_names %in% flowCore::parameters(ff)@data$name)]
    }
    sp_neutral <- diag(1, nrow = length(channel_names), ncol = length(channel_names))
    colnames(sp_neutral) <- unname(channel_names)
  } else {
    sp_neutral <- diag(1, nrow = nrow(sp), ncol = ncol(sp))
    colnames(sp_neutral) <- colnames(sp)
  }

  flowCore::keyword(ff)[[comp_mat_keyword]] <- sp_neutral
  flowCore::write.FCS(ff, fcs_file_path)
  message(fcs_file_path)
}
