global_vars <- c(".x", "$BTIM", "$ETIM", "$FIL", "$TOT", "Antigen",
  "antigen_case", "Antigen.Conjugate", "Antigen.x", "Antigen.y",
  "Box", "Box.x", "Box.y", "cell", "channel", "channel_mode", "channels",
  "cluster_1", "cluster_2", "config", "Conjugate", "conjugate_case",
  "Conjugate.x", "Conjugate.y", "count", "Count", "Count2", "depends",
  "desc", "diff_abs", "diff_sign", "diptest_pvalue_1", "diptest_pvalue_2",
  "diptest_pvalue_cluster", "diptest_pvalue_notcluster", "dir_exist",
  "eventsInside", "feature", "feature_order",
  "ff.list", "ff2", "FI", "file_exist", "FileDir", "FileName",
  "FilePath", "FlowJoFileName", "FlowJoGroup", "fluorochrome",
  "from", "GateDepth", "GateLevel",
  "grandparent", "grandparent_id", "GrandparentPath", "group",
  "group_order", "hash", "id", "ind", "label", "LocalFileName",
  "LocalFilePath", "Lot", "Lot.x", "Lot.y", "marker", "mean_1",
  "mean_2", "mean_cluster", "mean_diff",
  "mean_notcluster", "min.max.normalization", "n", "n_after", "n_before",
  "n_samples", "name", "name2", "ndesc", "NodeType", "old_id",
  "parent", "Parent", "parent_id", "ParentPath", "path", "pm",
  "pop", "Population", "PopulationFullPath", "PopulationFullPath2",
  "pval", "pval_sym", "pvalue", "rel", "rename", "row.num",
  "same_identity", "same_identity_and_filename", "sample_info",
  "sampleID", "sp", "to", "total", "TotalCount", "transformation",
  "transformation_pars", "type", "uri", "value", "values",
  "x", "xChannel", "xDesc", "xDim", "y", "yaxis", "yChannel",
  "yDesc", "yDim")

utils::globalVariables(global_vars)
